### PR TITLE
Add Base64 image sharing

### PR DESCRIPTION
**Pull request by chapayevdauren**
This solve #26

### CODE REVIEW

**Comment by andrerfneves** [comment]
Can we get this merged @EstebanFuentealba?

**Comment by andrerfneves** [comment]
@chapayevdauren can you fix conflicts so @EstebanFuentealba can merge?

**Comment by chapayevdauren** [comment]
@andrerfneves which conflict I need to fix?

**Comment by andrerfneves** [comment]
@chapaevdauren I'm not sure. but it says there's a branch conflict. So fetch origin master and merge it with your branch and you should see the conflict.

**Comment by chapayevdauren** [comment]
My master branch is up to date

**Pull request closed without merging**
