### PR TITLE
Add option to share file for android and iOS

### PR DESCRIPTION
**Pull request by superandrew213**
This allows to share and open files with available apps. My use case was to send to Instagram.

### CODE REVIEW

**Comment by bcalik** [comment]
Is it possible to pass share_File param as url to image? Thanks.

**Comment by superandrew213** [comment]
@bcalik yes. Share_file param is the absolute url of the image without ```file:``` prefix. On iOS you can pass this as the uri. On android I think you have to add the ```file:``` prefix.

**Comment by bcalik** [comment]
@superandrew213 Thank you. I mean an image which is not stored on the device, a http url.

**Comment by superandrew213** [comment]
Then it won't work. It's only meant to work for internally stored files. For urls you would need to use share_URL.

Other option would be to download and store the file using react-native-fs and then use share_file.

**Comment by superandrew213** [comment]
@EstebanFuentealba what do you think? Can we add this option?

**Comment by vcalvello** [comment]
Hey guys! any news on this?

**Comment by superandrew213** [comment]
This package has changed quite but since I forked it. I will have a look at it again but it will take me a bit. Feel free to use my fork in the meantime.

**Comment by adamkdean** [comment]
@EstebanFuentealba this was closed on 22 Sep – could you elaborate why? Was Instagram integrated?

**Comment by vinayan3** [comment]
If the URL is like `file://something.something` then there is an intention of sharing a document. Instagram shows up in the list.  It looks like this:
http://i.imgur.com/UxT7lQj.png

**Comment by airman00** [comment]
Does this work for video? The Menu appears with all the options, except Instagram. I've checked the More submenu too looking for IG. I can share to FB and Photo Library just fine.

If I save the video to Photos on the device, I can actually share to Instagram from the Photos app.

I've tried with .mp4 and .mov format for the video. the video is 13 seconds long.

can someone try it with video? Curious if its an error on my end or a bug in the library.

Thanks!

**Comment by iamakimmer** [comment]
Will this PR be merged in? or what is needed to get this up and running?

**Comment by danrice01** [comment]
@airman00 Did you get this working with video in the end?

**Comment by airman00** [comment]
@danrice01 
The trick is to make sure you don't set a title or subject.

Here's an example that worked for me
`  shareVideo(){
      var finalVideoPath = 'file://' + RNFS.DocumentDirectoryPath + '/finalVideo.mp4'

      let shareOptions = {
        //  title: "React Native",  // don't put a title
          message: "Hola mundo",
          url: finalVideoPath,
          type: "video/mp4",
       //   subject: "Share Link" //  don't put a subject
        };
    Share.open(shareOptions);

    `

**Comment by danrice01** [comment]
@airman00 Thank you. Working :)

**Comment by sibelius** [comment]
any changes we get this in?

**Comment by nidzola-nikolaz** [comment]
any progress on this?

**Comment by ataillefer** [comment]
Guys, this PR couldn't be merged as it stands because as @superandrew213 said the fork was made more than 1 year ago! Since then, `react-native-share` has integrated file sharing which is the purpose of this PR.

**Pull request closed without merging**
