### PR TITLE
Fix share dialog title missing in android

### PR DESCRIPTION
**Pull request by fschai89**
When open the share dialog, the default title is "Share". This a quick fix to able to change the default title.

### CODE REVIEW

**Comment by jabm111** [comment]
Hi @EstebanFuentealba,

This would fix #178,  any possibility of merging this soon?

Thanks!

**Comment by jgcmarins** [comment]
@fschai89 did you test this in production?

**Comment by lucasbento** [comment]
@jgcmarins, @jabm111: just tested it and it works, can you merge this, @sibelius?

Thanks for this, @jabm111!

**Comment by MuhammadMattiullah** [comment]
@fschai89 Title still not working. I am adding a title key in the share options object but it's not appearing as a title in IOS and Android.

const shareUrl = ${config.shareUrl}/conversations/${conversation.id};
const title = conversation.subject || conversation.body.slice(0, 60);
const shareOptions = {
title: title,
url: shareUrl,
};
Share.open(shareOptions);
But when i pass message and url it concatenate the message and url as a title.
But i want to show only the title.
How can i do this?

**Pull request merged**
